#ifndef DUBPROJECT_GLOBAL_H
#define DUBPROJECT_GLOBAL_H

#if defined(DUBPROJECT_LIBRARY)
#  define DUBPROJECT_EXPORT Q_DECL_EXPORT
#else
#  define DUBPROJECT_EXPORT Q_DECL_IMPORT
#endif

#endif // DUBPROJECT_GLOBAL_H
