#ifndef DUBPROJECT_GLOBAL_H
#define DUBPROJECT_GLOBAL_H

#include <QtGlobal>

#if defined(DUBPROJECT_LIBRARY)
#  define DUBPROJECTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DUBPROJECTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DUBPROJECT_GLOBAL_H
